=== xbcxs/javars/src/test/java/com/xbcxs/xsd/menu.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.sysware.com/eap/menu"
           elementFormDefault="qualified">

    <xs:element name="menus" type="menuinfo"/>
    <xs:complexType name="menuinfo">
        <xs:sequence>
            <xs:element ref="menu" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="menu">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="uri" type="xs:string"/>
            <xs:element name="name" type="xs:string" minOccurs="0"/>
            <xs:element name="code" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    </xs:element>

</xs:schema>

=== xbcxs/javars/src/test/java/com/xbcxs/xsd/menu.xml
<?xml version="1.0"?>
<menus xmlns="http://www.sysware.com/eap/menu"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sysware.com/eap/menu http://www.sysware.com/eap/menu/menu.xsd">
    <menu>
        <uri></uri>
        <description></description>
    </menu>
    <menu>
        <uri></uri>
        <description></description>
    </menu>
    <menu>
        <uri></uri>
        <description></description>
    </menu>
    <menu>
        <uri></uri>
        <description></description>
    </menu>

</menus>
